### 연예인 닮은 꼴 찾기
- 강아지상, 고양이상 남자 연예인 사진준비

In [80]:
import pandas as pd
import numpy as np
import cv2
import glob
import os
from rembg import remove
import matplotlib.pyplot as plt

In [51]:
# 주어진 디렉토리에 있는 항목들의 이름을 담고 있는 리스트를 반환

file_path = './zico/'
file_path2 = './baek/'
file_path3 = './kang/'
file_path4 = './xiu/'

file_names = os.listdir(file_path)
file_names

['005240010170.jpg',
 '03-580754.jpg',
 '03.14586219.1.jpg',
 '03.30803325.1.jpg',
 '114761143.4.jpg',
 '1355134729_432219.jpg',
 '1382165883_591094.jpg',
 '1447590352467581.jpg',
 '1571188451_1498300.jpg',
 '194514_186079_135.jpg',
 '197229_188543_0209.jpg',
 '201407231732771957_53cf736698962.jpg',
 '201409151006770373_54163ba0b2270.jpg',
 '20141107001402219_1.jpg',
 '201504140386245.jpg',
 '20151103001541_0.jpg',
 '20160512072620_1.jfif',
 '20161008000154_0.jpg',
 '20161024162129_D.jfif',
 '20161112504827.jpg',
 '20170204140323780xhiq.jpg',
 '20181123093120432775.jpg',
 '20191008134016450xeuw.jpg',
 '2020060518491129521_00_679.jpg',
 '20200914509634.jpg',
 '20201225054215122wfxt.jpg',
 '2022-KOREA-ZICO_LP-FWMH-1-Desktop.jpg',
 '2022080101000149300008541.jpg',
 '20220801520183.jpg',
 '2022112400245_2.jpg',
 '20230228104733082sgpt.jpg',
 '228834_218384_0804.jpg',
 '24379_31790_1320.jpg',
 '246368_245910_5213.jpg',
 '269MOTMLG8_5.jpg',
 '295835_365714_2700.jpg',
 '30423_58771_467.jpg',


### 파일 이름을 동일한 형식으로 변환하기

- 강아지상 남자연예인 전처리 과정

In [52]:
i = 1
for name in file_names:
    src = os.path.join(file_path, name)
    dst = 'm_cat_'+str(83+i)+'.jpg'
    dst = os.path.join(file_path, dst)
    os.rename(src, dst)
    i += 1


# 파일 이름 변경

In [141]:
file_path = './zico/'
file_path2 = './baek/'
file_path3 = './kang/'
file_path4 = './xiu/'

file_names = os.listdir(file_path2)
file_names

['m_dog_100.jpg',
 'm_dog_101.jpg',
 'm_dog_102.jpg',
 'm_dog_103.jpg',
 'm_dog_104.jpg',
 'm_dog_105.jpg',
 'm_dog_106.jpg',
 'm_dog_107.jpg',
 'm_dog_108.jpg',
 'm_dog_109.jpg',
 'm_dog_110.jpg',
 'm_dog_111.jpg',
 'm_dog_112.jpg',
 'm_dog_113.jpg',
 'm_dog_114.jpg',
 'm_dog_115.jpg',
 'm_dog_116.jpg',
 'm_dog_117.jpg',
 'm_dog_118.jpg',
 'm_dog_119.jpg',
 'm_dog_120.jpg',
 'm_dog_121.jpg',
 'm_dog_122.jpg',
 'm_dog_123.jpg',
 'm_dog_124.jpg',
 'm_dog_125.jpg',
 'm_dog_126.jpg',
 'm_dog_127.jpg',
 'm_dog_128.jpg',
 'm_dog_129.jpg',
 'm_dog_130.jpg',
 'm_dog_131.jpg',
 'm_dog_132.jpg',
 'm_dog_133.jpg',
 'm_dog_134.jpg',
 'm_dog_135.jpg',
 'm_dog_136.jpg',
 'm_dog_137.jpg',
 'm_dog_138.jpg',
 'm_dog_139.jpg',
 'm_dog_140.jpg',
 'm_dog_141.jpg',
 'm_dog_142.jpg',
 'm_dog_143.jpg',
 'm_dog_144.jpg',
 'm_dog_145.jpg',
 'm_dog_146.jpg',
 'm_dog_147.jpg',
 'm_dog_148.jpg',
 'm_dog_149.jpg',
 'm_dog_150.jpg',
 'm_dog_151.jpg',
 'm_dog_152.jpg',
 'm_dog_153.jpg',
 'm_dog_154.jpg',
 'm_dog_15

### 이미지 전처리

In [142]:
dstList1=[]
for name in file_names:
    # 1. grayscale
    imgData=cv2.imread(file_path2+name,cv2.IMREAD_GRAYSCALE)
    
    # 2. resize
    imgData=cv2.resize(imgData,dsize=(100,100))
    
    # 3. remove
    output=remove(imgData)

    # 4. 회전
    for degree in range(0,360,10):
        matrix=cv2.getRotationMatrix2D((50,50),degree,1)
        dst=cv2.warpAffine(output,matrix,(100,100))
        dstList1.append(dst)

In [143]:
dstList1255=[i/255 for i in dstList1]
dstList1255=[i.flatten() for i in dstList1255]

In [144]:
for i in range(len(dstList1255)):
    dstList1255[i]=np.append(dstList1255[i],1)

In [145]:
dstList1255

[array([0.        , 0.        , 0.        , ..., 0.01176471, 0.01568627,
        1.        ]),
 array([0., 0., 0., ..., 0., 0., 1.]),
 array([0., 0., 0., ..., 0., 0., 1.]),
 array([0., 0., 0., ..., 0., 0., 1.]),
 array([0., 0., 0., ..., 0., 0., 1.]),
 array([0., 0., 0., ..., 0., 0., 1.]),
 array([0., 0., 0., ..., 0., 0., 1.]),
 array([0., 0., 0., ..., 0., 0., 1.]),
 array([0., 0., 0., ..., 0., 0., 1.]),
 array([0.        , 0.        , 0.        , ..., 0.69411765, 0.89411765,
        1.        ]),
 array([0., 0., 0., ..., 0., 0., 1.]),
 array([0., 0., 0., ..., 0., 0., 1.]),
 array([0., 0., 0., ..., 0., 0., 1.]),
 array([0., 0., 0., ..., 0., 0., 1.]),
 array([0., 0., 0., ..., 0., 0., 1.]),
 array([0., 0., 0., ..., 0., 0., 1.]),
 array([0., 0., 0., ..., 0., 0., 1.]),
 array([0., 0., 0., ..., 0., 0., 1.]),
 array([0., 0., 0., ..., 0., 0., 1.]),
 array([0., 0., 0., ..., 0., 0., 1.]),
 array([0., 0., 0., ..., 0., 0., 1.]),
 array([0., 0., 0., ..., 0., 0., 1.]),
 array([0., 0., 0., ..., 0., 0

- 고양이상 남자연예인 전처리 과정

In [146]:
file_path = './zico/'
file_path2 = './baek/'
file_path3 = './kang/'
file_path4 = './xiu/'

file_names = os.listdir(file_path3)
file_names

['m_dog_1.jpg',
 'm_dog_10.jpg',
 'm_dog_11.jpg',
 'm_dog_12.jpg',
 'm_dog_13.jpg',
 'm_dog_14.jpg',
 'm_dog_15.jpg',
 'm_dog_16.jpg',
 'm_dog_17.jpg',
 'm_dog_18.jpg',
 'm_dog_19.jpg',
 'm_dog_2.jpg',
 'm_dog_20.jpg',
 'm_dog_21.jpg',
 'm_dog_22.jpg',
 'm_dog_23.jpg',
 'm_dog_24.jpg',
 'm_dog_25.jpg',
 'm_dog_26.jpg',
 'm_dog_27.jpg',
 'm_dog_28.jpg',
 'm_dog_29.jpg',
 'm_dog_3.jpg',
 'm_dog_30.jpg',
 'm_dog_31.jpg',
 'm_dog_32.jpg',
 'm_dog_33.jpg',
 'm_dog_34.jpg',
 'm_dog_35.jpg',
 'm_dog_36.jpg',
 'm_dog_37.jpg',
 'm_dog_38.jpg',
 'm_dog_39.jpg',
 'm_dog_4.jpg',
 'm_dog_40.jpg',
 'm_dog_41.jpg',
 'm_dog_42.jpg',
 'm_dog_43.jpg',
 'm_dog_44.jpg',
 'm_dog_45.jpg',
 'm_dog_46.jpg',
 'm_dog_47.jpg',
 'm_dog_48.jpg',
 'm_dog_49.jpg',
 'm_dog_5.jpg',
 'm_dog_50.jpg',
 'm_dog_51.jpg',
 'm_dog_52.jpg',
 'm_dog_53.jpg',
 'm_dog_54.jpg',
 'm_dog_55.jpg',
 'm_dog_56.jpg',
 'm_dog_57.jpg',
 'm_dog_58.jpg',
 'm_dog_59.jpg',
 'm_dog_6.jpg',
 'm_dog_60.jpg',
 'm_dog_61.jpg',
 'm_dog_62.jpg',
 'm

In [147]:
dstList2=[]
for name in file_names:
    # 1. grayscale
    imgData=cv2.imread(file_path3+name,cv2.IMREAD_GRAYSCALE)
    
    # 2. resize
    imgData=cv2.resize(imgData,dsize=(100,100))
    
    # 3. remove
    output=remove(imgData)

    # 4. 회전
    for degree in range(0,360,10):
        matrix=cv2.getRotationMatrix2D((50,50),degree,1)
        dst=cv2.warpAffine(output,matrix,(100,100))
        dstList2.append(dst)

In [148]:
dstList2255=[i/255 for i in dstList2]
dstList2255=[i.flatten() for i in dstList2255]

In [149]:
for i in range(len(dstList2255)):
    dstList2255[i]=np.append(dstList2255[i],1)

- [3] list 합치기

In [150]:
dstList1255.extend(dstList2255)

- [4] csv로 저장

In [151]:
import csv
with open("dog.csv","w") as f:
    writer = csv.writer(f)
    
    for i in dstList1255:
        writer.writerow(i)